### ISSUE TITLE
Getting null on Android

### ISSUE THREAD

**Issue by DimitrisMpanis** [caiopo/flutter-installer-info#1]
Flutter (Channel master, 1.24.0-4.0.pre.51, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-GR)

`
    print("Getting installer info");
    try {
      var installerInfo = await getInstallerInfo();
      print(installerInfo);
      print(installerInfo.installerName);

    } catch (error) {
      print(error);

    }

`

The console prints

I/flutter (17452): Getting installer info
W/.lazyland.yatz(17452): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
I/flutter (17452): null
I/flutter (17452): NoSuchMethodError: The getter 'installerName' was called on null.
I/flutter (17452): Receiver: null
I/flutter (17452): Tried calling: installerName

**Comment by caiopo** [comment]
Hi there!

Yeah, that's intended. On Android sometimes it's not possible to determine what app was used to install your app (when `context.getInstallerPackageName()` returns null), so this library follows the same behavior. Usually it will return null when installing using `flutter run`, `adb`, or Android Studio. I will add this to the docs soon.


You can fix that code by testing for null before accessing the `installerName`:

```dart
final installerInfo = await getInstallerInfo();

if (installerInfo == null) {
  // Could not determine the installer
} else {
  // Installer discovered
}
```

Or by using null-safe access, e.g.:

```dart
print(installerInfo?.installerName);
```

I'll close this issue for now. Feel free to create another issue or reopen this one if you find a bug or need some help.
